Added map in the landing page
technojam/world-clock pull request #5
Opened 2020-09-30 19:19 UTC by mohitbhata12

I have added the itnteractive map , please review it.

2020-09-30 19:37 UTC, surajcool203 approved these changes

2020-09-30 21:38 UTC, surajcool203 approved these changes

2020-09-30 22:25 UTC, surajcool203 requested changes
get us the ss of the changes which you have made.

2020-10-02 09:38 UTC, codebloded commented
@mohitbhata12  please add a ss regarding what your changes ..and remove conflicts

2020-10-02 09:51 UTC, closed without merging